import { Inter } from 'next/font/google';
import './globals.css';
import Provider from "@/components/Provider";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen mx-auto max-w-6xl flex flex-col bg-white   dark:bg-gray-900">
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
